### ISSUE TITLE
2 Instances of Image Widget, both looking at Folders, both marked as Play Until Done, first image in the folder is always skipped

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-image#71]
<b>How it works now:</b>
1. Set up a Presentation with 2 instances of the Rise Vision Image Widget, both looking at folders, both set to Play Until Done.
2. Play the Presentation on a Display. Notice that the folders never play the first image in the folder, they always skip it, or shows it very briefly Also, it shows the last image in the folder twice, once when the Widget starts, and once when it ends.

Presentation to test with: https://apps.risevision.com/editor/workspace/78d43946-9f0a-42b5-a152-0f14bd5660af/?cid=556323b8-984c-4127-aa08-4d73d019bcb8

This was brought up by this user in the forum:  https://community.risevision.com/rise_vision_inc/topics/playlist-with-multiple-image-widgets-has-timing-problem

<b>How it should work:</b>
All images in each folder should show 1 time when the Widget is playing, before moving to the next instance of the Widget.

**Comment by alanclayton** [comment]
Fixed w/ Chrome 50.0.2661.102

**Comment by robb-price** [comment]
@alanclayton Since we are back on Chrome 49, this is still an issue.

**Comment by ByronDarlison** [comment]
@robb-price @alanclayton is this now resolved with the release of 51?

**Comment by robb-price** [comment]
@ByronDarlison @alanclayton We will retest with 51 today to confirm and update the issue accordingly.

**Comment by robb-price** [comment]
@ByronDarlison @alanclayton Confirmed that this is fixed with Chromium 51. Closing the issue.
